### ISSUE TITLE
TypeError: 'Structure' object is not subscriptable

### ISSUE THREAD

**Issue by miguelwon** [centricular/gstwebrtc-demos#140]
After opening a server at [webrtc.nirbheek.in](https://webrtc.nirbheek.in) I tried to run `sendrecv.py` and got the error:

```
(env) pi@raspberrypi:~/experiments/webrtc/gstwebrtc-demos/sendrecv/gst $ python webrtc-sendrecv.py --server wss://webrtc.nirbheek.in:8443 '7484'
entrou 1 <__gi__.GstWebRTCBin object at 0xb5697d50 (GstWebRTCBin at 0x209a118)>

** (python:30009): CRITICAL **: 02:08:13.665: file gstdtlsagent.c: line 192 (gst_dtls_agent_init): should not be reached

** (python:30009): CRITICAL **: 02:08:13.665: gst_dtls_agent_set_property: assertion 'self->priv->ssl_context' failed

** (python:30009): CRITICAL **: 02:08:13.665: gst_dtls_connection_set_property: assertion 'priv->ssl' failed

** (python:30009): CRITICAL **: 02:08:13.666: gst_dtls_connection_set_property: assertion 'priv->ssl' failed

** (python:30009): CRITICAL **: 02:08:13.674: gst_dtls_agent_get_certificate_pem: assertion 'GST_IS_DTLS_CERTIFICATE (self->priv->certificate)' failed

** (python:30009): CRITICAL **: 02:08:13.674: _generate_fingerprint_from_certificate: assertion 'certificate != NULL' failed

** (python:30009): CRITICAL **: 02:08:13.675: gst_dtls_connection_set_property: assertion 'priv->ssl' failed

** (python:30009): CRITICAL **: 02:08:13.676: gst_dtls_connection_set_property: assertion 'priv->ssl' failed

** (python:30009): CRITICAL **: 02:08:13.681: gst_dtls_agent_get_certificate_pem: assertion 'GST_IS_DTLS_CERTIFICATE (self->priv->certificate)' failed

** (python:30009): CRITICAL **: 02:08:13.681: _generate_fingerprint_from_certificate: assertion 'certificate != NULL' failed
!!! <Gst.Structure object at 0xb5693308 (GstStructure at 0xb1870970)>
Traceback (most recent call last):
  File "webrtc-sendrecv.py", line 54, in on_offer_created
    offer = reply['offer']
TypeError: 'Structure' object is not subscriptable

```

## I'm running the following OS:
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

**Comment by XiagenFeng** [comment]
With Ubuntu 18.04, I encounter the same 
  File "webrtc-sendrecv.py", line 54, in on_offer_created
    offer = reply['offer']
TypeError: 'Structure' object is not subscriptable


With the webrtc-sendrecv.py
But the corresponding webrtc-sendrecv binary built from webrtc-sendrecv.c works fine.

@miguelwon Maybe you can try to build the C version

**Comment by miguelwon** [comment]
I tried but also got a bunch of errors...

**Comment by XiagenFeng** [comment]
> I tried but also got a bunch of errors...

Would you try the following one line patch?
https://github.com/centricular/gstwebrtc-demos/pull/142/commits/41d9b0ed32027592de69fa5100bbf04037af8cdb

In my environment, the python version works with the above patch

**Comment by ystreet** [comment]
You need a new enough version of gst-python to be able to subscript GstStructures.

**Comment by XiagenFeng** [comment]
@ystreet Thanks for your insight:)
