### ISSUE TITLE
DTLS error on RaspberryPi

### ISSUE THREAD

**Issue by mohamednibrahim** [centricular/gstwebrtc-demos#219]
Hi,
I'm trying to run the Python example code.I'm using Python 3.7.  I'm getting the below error: 
** (python3:2134): CRITICAL **: 15:05:12.524: file gstdtlsagent.c: line 192 (gst_dtls_agent_init): should not be reached

** (python3:2134): CRITICAL **: 15:05:12.525: gst_dtls_agent_set_property: assertion 'self->priv->ssl_context' failed

** (python3:2134): CRITICAL **: 15:05:12.526: gst_dtls_connection_set_property: assertion 'priv->ssl' failed

** (python3:2134): CRITICAL **: 15:05:12.529: gst_dtls_connection_set_property: assertion 'priv->ssl' failed

** (python3:2134): CRITICAL **: 15:05:12.542: gst_dtls_agent_get_certificate_pem: assertion 'GST_IS_DTLS_CERTIFICATE (self->priv->certificate)' failed

** (python3:2134): CRITICAL **: 15:05:12.542: _generate_fingerprint_from_certificate: assertion 'certificate != NULL' failed

** (python3:2134): CRITICAL **: 15:05:12.545: gst_dtls_connection_set_property: assertion 'priv->ssl' failed

** (python3:2134): CRITICAL **: 15:05:12.547: gst_dtls_connection_set_property: assertion 'priv->ssl' failed

** (python3:2134): CRITICAL **: 15:05:12.558: gst_dtls_agent_get_certificate_pem: assertion 'GST_IS_DTLS_CERTIFICATE (self->priv->certificate)' failed

** (python3:2134): CRITICAL **: 15:05:12.559: _generate_fingerprint_from_certificate: assertion 'certificate != NULL' failed
Traceback (most recent call last):
  File "sendrecv/gst/webrtc_sendrecv.py", line 57, in on_offer_created
    offer = reply['offer']
TypeError: 'Structure' object is not subscriptable
^CTraceback (most recent call last):
  File "sendrecv/gst/webrtc_sendrecv.py", line 190, in <module>
    res = loop.run_until_complete(c.loop())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)

**Comment by mohamednibrahim** [comment]
Problem solved via : export OPENSSL_CONF=""
