### ISSUE TITLE
free(): invalid pointer with python3 and webrtc-sendrecv.py

### ISSUE THREAD

**Issue by Jackovic** [centricular/gstwebrtc-demos#79]
Hello,

I just tried :
```
$ python3 webrtc-sendrecv.py 7497
```

But I get :
```
...
...
...
free(): invalid pointer
Abandon (core dumped)
```

I am using GStreamer 1.15.1 and I don't know if this issue is fixed or if there is a workaround ?
I saw a similar issue closed but didn't see solution.
Any clue ?
Thanks !

Here a backtrace with gdb :

```
$ gdb python3
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...(no debugging symbols found)...done.
(gdb) run webrtc-sendrecv.py 7497
Starting program: /usr/bin/python3 webrtc-sendrecv.py 7497
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff185f700 (LWP 10767)]
[New Thread 0x7fffe5b6e700 (LWP 10769)]
[New Thread 0x7fffdec88700 (LWP 10770)]
[New Thread 0x7fffde487700 (LWP 10771)]
[New Thread 0x7fffddc86700 (LWP 10772)]
[New Thread 0x7fffdd485700 (LWP 10773)]
[New Thread 0x7fffdcc84700 (LWP 10774)]
[New Thread 0x7fffc7fff700 (LWP 10775)]
[New Thread 0x7fffc77fe700 (LWP 10776)]
[New Thread 0x7fffc69ca700 (LWP 10777)]
[New Thread 0x7fffc61c9700 (LWP 10778)]
[New Thread 0x7fffc59c8700 (LWP 10779)]
[New Thread 0x7fffc51c7700 (LWP 10780)]
[New Thread 0x7fffc49c6700 (LWP 10781)]
Sending offer:
v=0
o=- 2134037024467758539 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=group:BUNDLE video0 audio1
m=video 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:7tUa8voqRVXJ6S9MBe+vqtlK5sbWF8Ip
a=ice-pwd:JKmrqgcsJMVCrKw32oI3+bfF0NQvoES9
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:97 VP8/90000
a=rtcp-fb:97 nack pli
a=framerate:30
a=ssrc:3696890204 msid:user302002250@host-1a90e139 webrtctransceiver0
a=ssrc:3696890204 cname:user302002250@host-1a90e139
a=mid:video0
a=fingerprint:sha-256 10:7B:1F:0A:53:96:4C:63:83:3C:0C:AD:5C:C4:E7:24:53:09:A8:B4:1A:30:76:ED:2F:C6:08:16:FB:79:35:18
m=audio 0 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:7tUa8voqRVXJ6S9MBe+vqtlK5sbWF8Ip
a=ice-pwd:JKmrqgcsJMVCrKw32oI3+bfF0NQvoES9
a=bundle-only
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:96 OPUS/48000/2
a=rtcp-fb:96 nack pli
a=fmtp:96 sprop-maxcapturerate=48000;sprop-stereo=0
a=ssrc:4037710646 msid:user302002250@host-1a90e139 webrtctransceiver1
a=ssrc:4037710646 cname:user302002250@host-1a90e139
a=mid:audio1
a=fingerprint:sha-256 10:7B:1F:0A:53:96:4C:63:83:3C:0C:AD:5C:C4:E7:24:53:09:A8:B4:1A:30:76:ED:2F:C6:08:16:FB:79:35:18

[New Thread 0x7fffaffff700 (LWP 10782)]
Received answer:
v=0
o=- 6794521953566038920 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE video0 audio1
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:UxlJ
a=ice-pwd:xnCtopozHLxgzpVsg8Ji6oCq
a=ice-options:trickle
a=fingerprint:sha-256 C9:DA:E4:42:4C:F2:82:90:D0:6D:D0:48:23:58:7C:4C:47:23:15:AC:0E:3B:AA:F2:11:0D:C0:D9:D6:9A:64:8F
a=setup:active
a=mid:video0
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:97 VP8/90000
a=rtcp-fb:97 nack pli
m=audio 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:UxlJ
a=ice-pwd:xnCtopozHLxgzpVsg8Ji6oCq
a=ice-options:trickle
a=fingerprint:sha-256 C9:DA:E4:42:4C:F2:82:90:D0:6D:D0:48:23:58:7C:4C:47:23:15:AC:0E:3B:AA:F2:11:0D:C0:D9:D6:9A:64:8F
a=setup:active
a=mid:audio1
a=recvonly
a=rtcp-mux
a=rtpmap:96 OPUS/48000/2
a=fmtp:96 minptime=10;useinbandfec=1

double free or corruption (out)

Thread 1 "python3" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7a22e97 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7a24801 in __GI_abort () at abort.c:79
#2  0x00007ffff7a6d897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7b9ab9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff7a7490a in malloc_printerr (str=str@entry=0x7ffff7b9c870 "double free or corruption (out)") at malloc.c:5350
#4  0x00007ffff7a7be75 in _int_free (have_lock=0, p=0x1002c60, av=0x7ffff7dcfc40 <main_arena>) at malloc.c:4278
#5  0x00007ffff7a7be75 in __GI___libc_free (mem=0x1002c70) at malloc.c:3124
#6  0x00007ffff013d658 in gst_sdp_message_init (msg=msg@entry=0xfd28b0)
    at gstsdpmessage.c:281
#7  0x00007ffff013dab2 in gst_sdp_message_uninit (msg=msg@entry=0xfd28b0)
    at gstsdpmessage.c:314
#8  0x00007ffff013dbce in gst_sdp_message_free (msg=0xfd28b0) at gstsdpmessage.c:446
#9  0x00007fffebbb3b92 in gst_webrtc_session_description_free (desc=0xfd3780)
    at rtcsessiondescription.c:94
#10 0x00007ffff3d7c1bb in g_boxed_free () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff421efd0 in  ()
    at /usr/lib/python3/dist-packages/gi/_gi.cpython-36m-x86_64-linux-gnu.so
#12 0x0000000000565cda in _PyCFunction_FastCallDict ()
#13 0x00000000005a3761 in _PyObject_FastCallDict ()
#14 0x000000000061a2bd in  ()
#15 0x000000000055e895 in PyObject_CallFinalizerFromDealloc ()
#16 0x0000000000554567 in  ()
#17 0x0000000000586108 in  ()
#18 0x000000000058c702 in  ()
#19 0x0000000000507e02 in _PyEval_EvalFrameDefault ()
#20 0x000000000058c5d8 in  ()
#21 0x00007ffff4a6faf7 in  ()
    at /usr/lib/python3.6/lib-dynload/_asyncio.cpython-36m-x86_64-linux-gnu.so
#22 0x000000000059ebbe in PyObject_Call ()
#23 0x0000000000507c17 in _PyEval_EvalFrameDefault ()
#24 0x0000000000502209 in  ()
#25 0x0000000000502f3d in  ()
#26 0x0000000000506859 in _PyEval_EvalFrameDefault ()
#27 0x0000000000502209 in  ()
#28 0x0000000000502f3d in  ()
#29 0x0000000000506859 in _PyEval_EvalFrameDefault ()
#30 0x0000000000502209 in  ()
#31 0x0000000000502f3d in  ()
#32 0x0000000000506859 in _PyEval_EvalFrameDefault ()
#33 0x0000000000502209 in  ()
#34 0x0000000000502f3d in  ()
#35 0x0000000000506859 in _PyEval_EvalFrameDefault ()
#36 0x0000000000504c28 in  ()
#37 0x0000000000506393 in PyEval_EvalCode ()
#38 0x0000000000634d52 in  ()
#39 0x0000000000634e0a in PyRun_FileExFlags ()
#40 0x00000000006385c8 in PyRun_SimpleFileExFlags ()
---Type <return> to continue, or q <return> to quit---q
Quit
```

**Comment by MathieuDuponchelle** [comment]
Hello @Jackovic , my best guess is that the gir files you're using aren't up to date, I think this was fixed by https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/commit/0178354e6e8598ab14091103db832e23ee1bdfcc , you should triple check what gir files you are using :)

**Comment by Jackovic** [comment]
Hello Mathieu,

My gir files are :
gir1.2-gst-plugins-bad-1.0
gir1.2-gst-plugins-base-1.0

installed with apt on ubuntu 18.04.

I need to build them ? If yes, where can I find the sources ?

I installed gstreamer, gst-libav, gst-plugins-base, gst-plugins-good, gst-plugins-bad, gst-plugins-ugly, gst-python from source (version 1.15.1)

**Comment by Jackovic** [comment]
OK, I try to build gst-plugins-bad with --enable-introspection but I get this error :
Couldn't find include 'GstVideo-1.0.gir' (search path: '['../../../gst-libs', '/usr/local/share/gir-1.0', '/usr/local/share/gir-1.0', '/usr/local/share/gir-1.0', 'gir-1.0', '/usr/share/gir-1.0', '/usr/share/gir-1.0', '/usr/share/gir-1.0']')
Makefile:1251: recipe for target 'GstPlayer-1.0.gir' failed
make[4]: *** [GstPlayer-1.0.gir] Error 1
I dig...

**Comment by Jackovic** [comment]
OK, I got it !
I needed to build gstreamer and gst-plugins-base with "--enable-introspection".
Then I will be able to build  gst-plugins-bad with "--enable-introspection".

All "introspections" files go in /usr/local/lib/girepository-1.0 so I symlink them :
$ sudo ln -s /usr/local/lib/girepository-1.0/* /usr/lib/girepository-1.0/
I don't know if there is a better way, but now I can see the ball and listen noise in the browser ! :)

**Comment by MathieuDuponchelle** [comment]
Note that [gst-build](https://cgit.freedesktop.org/gstreamer/gst-build/) is a great solution when you wish to try out the latest version of GStreamer without messing up your system-wide install @Jackovic :)
